server:
  port: 18022
spring:
  application:
    name: hydra-code
  main:
    allow-bean-definition-overriding: true
  datasource:
    dynamic:
      druid:
        initial-size: 5
        max-active: 2000
        max-wait: 600000
        min-evictable-idle-time-millis: 300000
        min-idle: 5
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        validation-query: SELECT 1 FROM DUAL
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          password: Jgw*31500-2018.6
          url: jdbc:mysql://192.168.2.215:3306/platform_code?characterEncoding=utf-8&useSSL=false
          username: jgw
security:
  oauth2:
    client:
      client-id: dev
      client-secret: 123456
    resource:
      token-info-uri: http://localhost:10001/oauth/check_token